name: Bug Report
description: You are creating a Game with Flame but you are noticing some strange behavior, that it throws an unexpected exception, or that it is not working according to the specifications.
title: " "
labels: ["bug"]
assignees: ""
body:
  - type: markdown
    attributes:
      value: |
        When reporting a bug, please read this complete template and fill in all the questions in order to get a better response!
 - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Tell us, what happened?
      placeholder: Tell us what you see!
    validations:
      required: true
      
  - type: textarea
    id: expectation
    attributes:
      label: What do you expect?
      description: Also tell us, what behavior did you expect? 
      placeholder: Tell us what you want!
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: If you have any debug / error logging, please fill it here within the code block below
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true

# Steps to reproduce
<!-- This one is very important, please be very precise in how we can reproduce this bug -->
<!-- If possible please report steps based on the example from this plugin! -->
<!-- If you can make a minimal reproducible example it is incredibly helpful, the simplest way is to share a link from https://zapp.run, you can start from https://zapp.run/edit/flame where all dependencies are already set up. -->

# Flutter doctor output
<!-- Execute in a terminal and put output into code block below -->
```
Output of: flutter doctor -v
```

# More environment information
<!--
Create a list of more environment information, like:
* Flame version: 1.0.0
* Platform affected: android, ios, web
* Platform version affected: android 9, ios 13
-->

# More information
<!-- Do you have any other useful information about this bug report? Please write it down here -->
<!-- Possible helpful information: references to other sites/repositories -->
<!-- Are you interested in working on a PR for this? -->
